language: python
python: '3.6'
services:
- docker
sudo: true
addons:
  apt:
    packages:
    - python-pip
before_install:
- openssl aes-256-cbc -K $encrypted_797dcd9eb7ac_key -iv $encrypted_797dcd9eb7ac_iv
  -in .vault.enc -out .vault -d
install:
- sudo mkdir -p /etc/ansible/vault /etc/ansible/hosts
- sudo chown -R $USER /etc/ansible
- cp .vault /etc/ansible/vault/jenkins
- cp .inventory /etc/ansible/hosts/hosts
- pip install git+https://github.com/ansible/ansible
- pip install docker
- ansible --version
- which ansible
script:
- ansible-playbook site.yml --syntax-check
- ansible-playbook site.yml -t container
notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
