language: python
python: '3.6'
services:
- docker
sudo: false
addons:
  apt:
    packages:
    - python-pip
install:
- pip install ansible
- pip install docker
- ansible --version
- which ansible
- printf '[defaults]\nroles_path=../roles/' >ansible.cfg
- printf 'localhost ansible_connection=local ansible_python_interpreter=/home/travis/virtualenv/python3.6.3/bin/python'
  >inventory
script:
- ansible-playbook site.yml -i inventory --syntax-check
- ansible-playbook site.yml -i inventory -t container
notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
before_install:
- openssl aes-256-cbc -K $encrypted_797dcd9eb7ac_key -iv $encrypted_797dcd9eb7ac_iv
  -in .vault.enc -out .vault -d
