---
- name: Create or update secret key.
  docker_secret:
    name: jenkins.brick-house.org.key
    data: "{{ lookup('file', 'roles/actual/files/key.pem') }}"
    state: present
- name: Create or update certificate.
  docker_secret:
    name: jenkins.brick-house.org.crt
    data: "{{ lookup('file', 'roles/actual/files/cert.pem') }}"
    state: present
- name: Copy stack file.
  copy:
    src: stack.yml
    dest: "{{ stack_path }}"
    owner: duchess
    group: docker
- name: Deploy Jenkins Stack
  docker_stack:
    name: jenkins
    compose:
      - "{{ stack_path }}"
    state: present
  tags:
    - stack
