---
- name: Copy secret key to master.
  template:
    src: jenkins.brick-house.org.key
    dest: /tmp/jenkins.brick-house.org.key
- name: Create or update secret key.
  docker_secret:

- name: Copy stack file.
  copy:
    src: stack.yml
    dest: "{{ stack_path }}"
    owner: duchess
    group: docker
- name: Deploy Jenkins Stack
  docker_stack:
    name: jenkins
    compose:
      - "{{ stack_path }}"
    state: present
  tags:
    - stack
