---
- docker_image:
    name: jenkins/jenkins:alpine
    pull: yes
    state: present
- docker_container:
    image: jenkins/jenkins:alpine
    name: jenkins
    state: started
    volumes:
      - /srv/jenkins:/var/jenkins_home
