---
- name: Pull Jenkins image.
  docker_image:
    name: jenkins/jenkins:alpine
    pull: yes
    state: present
- name: Verify docker network.
  docker_network:
    name: money
    state: present
- name: Start Jenkins
  docker_container:
    image: jenkins/jenkins:alpine
    name: jenkins
    state: started
    volumes:
      - /srv/jenkins:/var/jenkins_home
