---
- name: Copy stack file.
  copy:
    src: stack.yml
    dest: "{{ stack_path }}"
    owner: duchess
    group: docker
- name: Deploy Jenkins Stack
  docker_stack:
    name: jenkins
    compose:
      - "{{ stack_path }}"
    state: present
  tags:
    - stack
