---
- name: Copy stack file.
  file:
    content: "{{ lookup('file', '/srv/jenkins.actual/roles/actual/files/stack.yml') }}"
    dest: "{{ stack_path }}"
    owner: duchess
    group: docker
- name: Deploy Jenkins Stack
  docker_stack:
    name: jenkins
    compose:
      - "{{ stack_path }}"
    state: present
  tags:
    - stack
  delegate_to: ucp.brick-house.org
