---
docker_env:
  COMPOSE_TLS_VERSION: TLSv1_2
  DOCKER_CERT_PATH: '/Users/duchess/Downloads/ucp-bundle-xander'
  DOCKER_HOST: 'tcp://ucp.brick-house.org:443'
  DOCKER_TLS_VERIFY: 1
ucp_ssh_pubkey: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAAEAQDZTiREa7hd0WrDl7/3cayED2\
  RpEMSbgaBhc0d6jOqU7GFyp1c3SOfGWJPFXjBbddPjwJHvdT7T7RgUc0+3genAmcsryFF1eo1JI5p\
  /QBF/OSnuL2/UT/RZn5fq0Wn9iqvIcEeqXFM7r+UuT+UVbXxv61xDanBwQ7saJcHw207cvQZ99sF2\
  ukfJ0fEdCSsiYdbMpnIvLovuKp4EOfIIdlcIRt0cf5+vrge2IA9yU5ZDnjARfytdQe6nJb5Da7S1e\
  Qhtn77p8ADwAZsqpCeYgg+VMUHGnZeZJKlyg59KXgTANTbhjl6OrakN9hSBGGw+f+/AY0yRNqLf0u\
  oMeGAR4vhS5R4/RpVqeC5CjmGelbwANKyMtqXn5wuXEzXSG2lhzGcpVuXL2sC3j68g0JeJmKm4Cot\
  CmUG1mr32n3p0+DcE45YN91JFBnYl2VspzsUgv+maVvEfoGbaFPxM3zafU9KkyhNR0DZCTjxfEwpm\
  qvYdG6At6zh5aZrkYfdOfTzld9wRNI8d0trgHKtER2YcbHmebkOMC2/6PFFCnv7sBEvMy2kemYl0T\
  p0dEt/qD+px+zahGVTkyJtYDWrOqMSkS1sVWM8Hhyld89zO4HXxEI4qrLvOaA9KIkif26/thk+vEi\
  IfXrFWZLJWnHdzRWGQEglDVi13d0QoQEqrjcN8oIWcwNktTJA9f7kHFcjMRGgsLA3VuWFHhgTTBrC\
  Wp8O3H2WJKTUAxVc2+Og8Wti2DCQ/qIa3lDDfOFPHZPdxNZ8ipGVs7Q0x5cG6wFRCVB7Q2APbxcZl\
  2ky9Hfsp0sV/YMoziYf3JbAG3rnL1oP/BXADcfyHe+BHFx7osFGT2DC8iipdX588knpTDobRBuSlt\
  DKg18Xl/rdE3kX4q067MftaEZndfOGlaivk5JkL7bWWau0KIQn+y/DeiE2K0PhUoydQwspzXymYES\
  WxuPM8/8On1OKYrbFQbZAzRVKE1sQQWnRo8QvVTvbUVHnbmvWV1pSp3mGEeLjsN8tfYdoZDFO8CkB\
  3LbaJBjty1+W0BDYHXYJ2DiiyEKDiMp9vHHnbg/4yEDWJ5M/3oBLeOTy63B82tFIXyoMPZbRrFsLv\
  So+9IB/2ANcCbeSEfWoV6Zxgv6YcTl9H9amJ3nASuUET2BvuUAHCDI1C8zlr/U7Bt6LPTjJ3QfmFX\
  RVHY1XHftljbyCVw7C34TWKaj/sQjLKeBvEne4cVxvGFpM5B8u7D+PYN3xw3ZUWgGQGcLPPwenKpb\
  necHV/1++7J0FYCO1IJmxlokOV5DydBt3Rb+2bbni1xIVs6aX7mfgDAzcFVuedoIN2G5lwphjk+MZ\
  LCOZgyJnBs+6XjX8BHvjnln4OPXkvoT2F duchess@manager"
stack_path: /home/duchess/stack.yml
