version: '3.7'
networks:
  main:
    driver: overlay
services:
  manager:
    command: '-jar /usr/share/jenkins/jenkins.war'
    deploy:
      replicas: 1
      labels:
        com.docker.lb.hosts: jenkins.brick-house.org
        com.docker.lb.networks: jenkins
        com.docker.lb.port: 8080
        org.brick-house: jenkins
      placement:
        constraints:
          - node.role==worker
    entrypoint: java
    image: jenkins/jenkins:alpine
    networks:
      - main
    user: root
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
      - 'home:/var/jenkins_home:rw'
volumes:
  home:
    name: home-vol
    labels:
      org.brick-house.jenkins.volume: "Jenkins Home"
