galaxy_info:
  author: Xander Harris
  description: Quick and dirty Jenkins CI
  company: Brick House
  license: Unlicense
  min_ansible_version: 2.4
  #
  # Provide a list of supported platforms, and for each platform a list of versions.
  # If you don't wish to enumerate all versions for a particular platform, use 'all'.
  # To view available platforms and versions (or releases), visit:
  # https://galaxy.ansible.com/api/v1/platforms/
  #
  platforms:
    - name: Ubuntu
      versions:
        - all
  galaxy_tags:
    - jenkins
dependencies: []
